-- Seed Data for Categories
INSERT INTO public.categories (emoji, name, examples) VALUES
('🔧', 'Tools & Equipment', 'Drills, saws, ladders, pressure washers, welding machines'),
('🏗️', 'Construction', 'Cement mixers, scaffolding, generators, concrete cutters'),
('🌿', 'Gardening', 'Lawn mowers, hedge trimmers, chainsaws, tillers'),
('🚗', 'Vehicles', 'Cars, bikes, scooters, vans, pickup trucks'),
('🚴', 'Cycles & Mobility', 'Bicycles, e-bikes, wheelchairs'),
('📷', 'Cameras & Photography', 'DSLR, mirrorless cameras, lenses, drones, tripods'),
('🎥', 'Audio & Video', 'Projectors, microphones, speakers, lighting kits'),
('💻', 'Electronics', 'Laptops, monitors, tablets, gaming PCs'),
('📱', 'Mobile Devices', 'Phones, iPads, smartwatches'),
('🎮', 'Gaming', 'PlayStations, Xbox, VR headsets, racing wheels'),
('🎵', 'Musical Instruments', 'Guitar, keyboard, drums, violin, DJ equipment'),
('👗', 'Fashion & Clothing', 'Suits, bridal wear, designer dresses, costumes'),
('💍', 'Jewelry & Accessories', 'Watches, necklaces, handbags, luxury accessories'),
('🎭', 'Party & Event Supplies', 'Chairs, tables, tents, decorations, sound systems'),
('🎪', 'Event Equipment', 'LED walls, stages, smoke machines, lighting'),
('🏕️', 'Camping & Outdoor', 'Tents, sleeping bags, BBQ grills, kayaks'),
('🏋️', 'Sports & Fitness', 'Treadmills, dumbbells, bicycles, cricket kits'),
('🏄', 'Adventure Gear', 'Surfboards, climbing gear, skiing equipment'),
('🏠', 'Home Appliances', 'Refrigerators, washing machines, air conditioners'),
('🍳', 'Kitchen Equipment', 'Coffee machines, ovens, mixers, catering equipment'),
('🛋️', 'Furniture', 'Sofas, beds, office desks, dining tables'),
('🏢', 'Office Equipment', 'Printers, scanners, projectors, conference equipment'),
('👶', 'Baby & Kids', 'Strollers, car seats, baby cribs, toys'),
('🐶', 'Pet Supplies', 'Pet carriers, cages, grooming tools'),
('🎨', 'Art & Creative', 'Easels, drawing tablets, sewing machines, 3D printers'),
('📚', 'Books & Study', 'Textbooks, exam materials, calculators'),
('🧪', 'Lab & Medical', 'Microscopes, hospital beds, wheelchairs (where legally appropriate)'),
('🚜', 'Agriculture', 'Tractors, sprayers, harvest equipment'),
('🚢', 'Water Sports', 'Boats, jet skis, paddle boards'),
('✈️', 'Travel Essentials', 'Luggage, travel adapters, camping backpacks'),
('🎁', 'Miscellaneous', 'Anything that doesn''t fit elsewhere')
ON CONFLICT DO NOTHING;
